version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo us-east-2
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 931728113463.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t pythonprojectrepo .
      - docker tag pythonprojectrepo:latest 931728113463.dkr.ecr.us-east-2.amazonaws.com/pythonprojectrepo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 931728113463.dkr.ecr.us-east-2.amazonaws.com/pythonprojectrepo:latest
